/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaguitutorial;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.time.Clock;
import java.time.LocalDateTime;
import java.util.Date;

/**
 *
 * @author w1726676
 */
public class FirstGUI extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    //whatever the users types into the fields it will be stored into these variables but not the userid
    // eventually when we assign it to the get text method
    private String username;
    private String firstname;
    private String lastname;
    private String email;
    private String password;
    private Date loginDateTime;

    public FirstGUI() {
        initComponents(); //initialises all the components of the page 
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        userName = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        uemail = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        upassword = new javax.swing.JPasswordField();
        passWord = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        ufname = new javax.swing.JTextField();
        lastName = new javax.swing.JLabel();
        ulname = new javax.swing.JTextField();
        submitAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adminname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userName.setText("Username");

        userEmail.setText("Email");

        uname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameActionPerformed(evt);
            }
        });

        uemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uemailActionPerformed(evt);
            }
        });

        submit.setText("Login");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        submit1.setText("Register");
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });

        upassword.setText("jPasswordField1");
        upassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upasswordActionPerformed(evt);
            }
        });

        passWord.setText("Password");

        firstName.setText("First Name");

        ufname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufnameActionPerformed(evt);
            }
        });

        lastName.setText("Last Name");

        submitAdmin.setText("Admin Login");
        submitAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAdminActionPerformed(evt);
            }
        });

        jLabel1.setText("If Admin (1) If User (0) ");

        adminname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminnameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(submit)
                                .addGap(8, 8, 8))
                            .addComponent(submit1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(submitAdmin)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(23, 23, 23)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(adminname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ufname)
                            .addComponent(upassword, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(uemail)
                            .addComponent(uname)
                            .addComponent(ulname))))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(userEmail))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(userName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(firstName))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(passWord))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lastName)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ufname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ulname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(userEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(passWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(submitAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminname)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameActionPerformed

    private void uemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uemailActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
//login button

        username = uname.getText(); //gets the user input and stores into this variable

        firstname = ufname.getText();
        lastname = ulname.getText();

        email = uemail.getText(); //gets user input and stores into this variable

        password = upassword.getText();
        ResultSet userResultSet = InsertTable.get(username, password);
        ResultSet userResultSet2 = InsertUserActivity.get2(username);
        //LTBE

        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill out both the username and password field."); //form validation
            return; //so the next if statement does not come into execution if this condition is not met
        }

        try {
            if (userResultSet.next() && userResultSet2.next()) { //LTBE
                JOptionPane.showMessageDialog(this, "User with this username is already registered... logging in user");
                InsertUserActivity.insertActivity(username, loginDateTime);

                JOptionPane.showMessageDialog(this, "User successfully logged in.");

                SecondGUI secondGUI = new SecondGUI(username, firstname, lastname, email, password); //constructor passing the username and password. Have the others just in case
                secondGUI.setVisible(true);
                this.setVisible(false); //setting the first gui (this) to be invis
                this.dispose(); // clear resources at each frame/UI component 
                //so closes first gui (this)
            } else {
                JOptionPane.showMessageDialog(this, "User does not exist Please register.");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }


    }//GEN-LAST:event_submitActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        //register button

        username = uname.getText(); //gets the user input and stores into this variable

        firstname = ufname.getText();
        lastname = ulname.getText();
        email = uemail.getText(); //gets user input and stores into this variable
        password = upassword.getText();
        ResultSet userResultSet = InsertTable.getUsername(username); //LTBE

        ResultSet userResultSet2 = InsertUserActivity.get2(username); //getting just username for the login
        if (username.equals("") || firstname.equals("") || lastname.equals("") || email.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(this, "Please fill out all the fields."); //form validation
            return; //so the next if statement does not come into execution if this condition is not met
        }
        String emailRegex = "^(.+)@(.+)$";
        if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(this, "Email is not in a valid format."); //form validation
            return;  //so the second gui does not appear till they meet this condition
        }

        try {
            if (userResultSet.next() && userResultSet2.next()) { //tells us if there is a next element
                JOptionPane.showMessageDialog(this, "User with this username is already registered.");
                return;
            } else {
                InsertTable.insert(username, firstname, lastname, email, password);
                InsertUserActivity.insertActivity(username, loginDateTime);
                JOptionPane.showMessageDialog(this, "User successfully registered.");

            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }

    }//GEN-LAST:event_submit1ActionPerformed

    private void upasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upasswordActionPerformed

    private void ufnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufnameActionPerformed

    private void submitAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAdminActionPerformed
        //admin panel
    }//GEN-LAST:event_submitAdminActionPerformed

    private void adminnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminnameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstGUI().setVisible(true);
            }
        });
    }

    private boolean isAdmin(String username) {
        try {
            Connection con = ConnectDB.getConnection();
            Statement stmt = con.createStatement();

            String sql = "select * from userDetailsTable where userId=" + username;
            ResultSet rs = stmt.executeQuery(sql);

            if (rs.next()) {
                String admin = rs.getString("admin");
                con.close();
                return admin.equals("1");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminname;
    private javax.swing.JLabel firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel passWord;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JButton submitAdmin;
    private javax.swing.JTextField uemail;
    private javax.swing.JTextField ufname;
    private javax.swing.JTextField ulname;
    private javax.swing.JTextField uname;
    private javax.swing.JPasswordField upassword;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
